# Site settings
title: gelatindesign

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gelatindesign.co.uk" # the base hostname & protocol for your site
permalink: :categories/:title

highlighter: rouge

category_archive:
  layout: category

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
future: false
exclude: [node_modules/]
