environment:
  development: %localhost%
  production:  %gelatindesign.co.uk%

path:
  controllers: controllers/
  models:      models/
  templates:   templates/
  views:       views/
  partials:    partials/
  web:         web/

routes:
  Pages:
    view: :string?/?