site:
  url: http://plan.localhost.com

database:
  protocol: mysql
  host:     localhost
  user:     
  pass:     
  name:     whatsourplan

email:
  transport: false
  default_address: info@gelatindesign.co.uk
  support_address: info@gelatindesign.co.uk

debug: true
cache: false
has_ssl: false

dev_ip_list:
  - %