url: http://www.whatsourplan.com

database:
  host: 
  user: 
  pass: 
  name: 

email:
  transport: false
  default_address: info@gelatindesign.co.uk
  support_address: info@gelatindesign.co.uk

debug: false
cache: true
has_ssl: false

dev_ip_list:
  - 93.97.190.53
  - 192.168.0.1