site:
  url: http://www.gelatindesign.co.uk

database:
  protocol: mysql
  host:     localhost
  user:     
  pass:     
  name:     gelatindesign

email:
  transport: false
  default_address: info@gelatindesign.co.uk
  support_address: info@gelatindesign.co.uk

debug: false
cache: false
has_ssl: false

dev_ip_list:
  - 